version: '3.8'

services:
  backend:
    build: .
    container_name: orus_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  dashboard:
    build: ./dashboard-orus
    container_name: orus_dashboard
    restart: always
    ports:
      - "3000:80"
